"""
Pydantic schemas for the Grin's Irrigation Platform.

This module exports all schema classes for request/response validation
and serialization in the API layer.

Phase 1: Customer Management schemas
Phase 2: Field Operations schemas (Service Offerings, Jobs, Staff)
Phase 3: Admin Dashboard schemas (Appointments, Dashboard Metrics)
Phase 6: AI Assistant schemas (AI, SMS)
Phase 7: Schedule AI Updates schemas (Schedule Explanation)
"""

from grins_platform.schemas.ai import (
    AIActionType,
    AIAuditLogEntry,
    AIAuditLogResponse,
    AIChatRequest,
    AIChatResponse,
    AIDecisionRequest,
    AIEntityType,
    AIUsageResponse,
    CategorizationSummary,
    CommunicationDraft,
    CommunicationDraftRequest,
    CommunicationDraftResponse,
    DeliveryStatus,
    EstimateBreakdown,
    EstimateGenerateRequest,
    EstimateGenerateResponse,
    GeneratedSchedule,
    JobCategorization,
    JobCategorizationRequest,
    JobCategorizationResponse,
    MessageType,
    ScheduleDay,
    ScheduledJob,
    ScheduleGenerateRequest,
    ScheduleGenerateResponse,
    ScheduleSummary,
    ScheduleWarning,
    SimilarJob,
    StaffAssignment,
    UserDecision,
)
from grins_platform.schemas.appointment import (
    AppointmentCreate,
    AppointmentListParams,
    AppointmentPaginatedResponse,
    AppointmentResponse,
    AppointmentUpdate,
    DailyScheduleResponse,
    StaffDailyScheduleResponse,
    WeeklyScheduleResponse,
)
from grins_platform.schemas.customer import (
    BulkPreferencesUpdate,
    BulkUpdateResponse,
    CustomerCreate,
    CustomerDetailResponse,
    CustomerFlagsUpdate,
    CustomerListParams,
    CustomerResponse,
    CustomerUpdate,
    PaginatedCustomerResponse,
    ServiceHistorySummary,
)
from grins_platform.schemas.dashboard import (
    DashboardMetrics,
    JobsByStatusResponse,
    PaymentStatusOverview,
    RecentActivityItem,
    RecentActivityResponse,
    RequestVolumeMetrics,
    ScheduleOverview,
    TodayScheduleResponse,
)
from grins_platform.schemas.job import (
    JobCreate,
    JobDetailResponse,
    JobListParams,
    JobResponse,
    JobStatusHistoryResponse,
    JobStatusUpdate,
    JobUpdate,
    PaginatedJobResponse,
    PriceCalculationResponse,
)
from grins_platform.schemas.property import (
    PropertyCreate,
    PropertyResponse,
    PropertyUpdate,
)
from grins_platform.schemas.schedule_explanation import (
    JobReadyToSchedule,
    JobsReadyToScheduleResponse,
    ParseConstraintsRequest,
    ParseConstraintsResponse,
    ParsedConstraint,
    ScheduleExplanationRequest,
    ScheduleExplanationResponse,
    StaffAssignmentSummary,
    UnassignedJobExplanationRequest,
    UnassignedJobExplanationResponse,
)
from grins_platform.schemas.service_offering import (
    PaginatedServiceResponse,
    ServiceListParams,
    ServiceOfferingCreate,
    ServiceOfferingResponse,
    ServiceOfferingUpdate,
)
from grins_platform.schemas.sms import (
    CommunicationsQueueItem,
    CommunicationsQueueResponse,
    SMSSendRequest,
    SMSSendResponse,
    SMSWebhookPayload,
)
from grins_platform.schemas.staff import (
    PaginatedStaffResponse,
    StaffAvailabilityUpdate,
    StaffCreate,
    StaffListParams,
    StaffResponse,
    StaffUpdate,
)

__all__ = [
    # Phase 6: AI Assistant
    "AIActionType",
    "AIAuditLogEntry",
    "AIAuditLogResponse",
    "AIChatRequest",
    "AIChatResponse",
    "AIDecisionRequest",
    "AIEntityType",
    "AIUsageResponse",
    "AppointmentCreate",
    "AppointmentListParams",
    "AppointmentPaginatedResponse",
    "AppointmentResponse",
    "AppointmentUpdate",
    "BulkPreferencesUpdate",
    "BulkUpdateResponse",
    "CategorizationSummary",
    "CommunicationDraft",
    "CommunicationDraftRequest",
    "CommunicationDraftResponse",
    "CommunicationsQueueItem",
    "CommunicationsQueueResponse",
    "CustomerCreate",
    "CustomerDetailResponse",
    "CustomerFlagsUpdate",
    "CustomerListParams",
    "CustomerResponse",
    "CustomerUpdate",
    "DailyScheduleResponse",
    "DashboardMetrics",
    "DeliveryStatus",
    "EstimateBreakdown",
    "EstimateGenerateRequest",
    "EstimateGenerateResponse",
    "GeneratedSchedule",
    "JobCategorization",
    "JobCategorizationRequest",
    "JobCategorizationResponse",
    "JobCreate",
    "JobDetailResponse",
    "JobListParams",
    "JobReadyToSchedule",
    "JobResponse",
    "JobStatusHistoryResponse",
    "JobStatusUpdate",
    "JobUpdate",
    "JobsByStatusResponse",
    "JobsReadyToScheduleResponse",
    "MessageType",
    "PaginatedCustomerResponse",
    "PaginatedJobResponse",
    "PaginatedServiceResponse",
    "PaginatedStaffResponse",
    "ParseConstraintsRequest",
    "ParseConstraintsResponse",
    "ParsedConstraint",
    "PaymentStatusOverview",
    "PriceCalculationResponse",
    "PropertyCreate",
    "PropertyResponse",
    "PropertyUpdate",
    "RecentActivityItem",
    "RecentActivityResponse",
    "RequestVolumeMetrics",
    "SMSSendRequest",
    "SMSSendResponse",
    "SMSWebhookPayload",
    "ScheduleDay",
    "ScheduleExplanationRequest",
    "ScheduleExplanationResponse",
    "ScheduleGenerateRequest",
    "ScheduleGenerateResponse",
    "ScheduleOverview",
    "ScheduleSummary",
    "ScheduleWarning",
    "ScheduledJob",
    "ServiceHistorySummary",
    "ServiceListParams",
    "ServiceOfferingCreate",
    "ServiceOfferingResponse",
    "ServiceOfferingUpdate",
    "SimilarJob",
    "StaffAssignment",
    "StaffAssignmentSummary",
    "StaffAvailabilityUpdate",
    "StaffCreate",
    "StaffDailyScheduleResponse",
    "StaffListParams",
    "StaffResponse",
    "StaffUpdate",
    "TodayScheduleResponse",
    "UnassignedJobExplanationRequest",
    "UnassignedJobExplanationResponse",
    "UserDecision",
    "WeeklyScheduleResponse",
]
