"""
Pydantic schemas for the AI scheduling system.

Defines request/response schemas for criteria evaluation, AI chat,
alerts/suggestions, change requests, pre-job intelligence, batch
scheduling, capacity/utilization, and configuration.

Validates: Requirements 1.1-1.9, 2.1-2.5, 9.1-9.10, 10.1-10.10,
11.1-11.5, 12.1-12.5, 14.1-14.10, 15.1-15.10, 23.1
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# --- Criteria Evaluation ---


class CriterionResult(BaseModel):
    """Result of evaluating a single criterion for a job-staff assignment."""

    criterion_number: int
    criterion_name: str
    score: float = Field(ge=0, le=100)
    weight: int = Field(ge=0, le=100)
    is_hard: bool
    is_satisfied: bool
    explanation: str


class ScheduleEvaluation(BaseModel):
    """Full evaluation of a schedule against all 30 criteria."""

    schedule_date: date
    total_score: float
    hard_violations: int
    criteria_scores: list[CriterionResult]
    alerts: list[AlertCandidate]


class RankedCandidate(BaseModel):
    """A staff candidate ranked by composite criteria score."""

    staff_id: UUID
    name: str
    composite_score: float
    criterion_breakdown: list[CriterionResult]


# --- Chat ---


class ChatRequest(BaseModel):
    """Request to the AI scheduling chat."""

    message: str
    session_id: UUID | None = None


class ScheduleChange(BaseModel):
    """A schedule change proposed by the AI."""

    change_type: str  # "add", "remove", "move", "swap"
    job_id: UUID | None = None
    staff_id: UUID | None = None
    old_slot: str | None = None
    new_slot: str | None = None
    explanation: str


class ChatResponse(BaseModel):
    """Response from the AI scheduling chat."""

    response: str
    schedule_changes: list[ScheduleChange] | None = None
    clarifying_questions: list[str] | None = None
    change_request_id: UUID | None = None


# --- Alerts ---


class ResolutionOption(BaseModel):
    """An available resolution action for an alert."""

    action: str
    label: str
    description: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class AlertCandidate(BaseModel):
    """A candidate alert generated by the alert engine before persistence."""

    alert_type: str
    severity: str  # "critical" or "suggestion"
    title: str
    description: str
    affected_job_ids: list[UUID] = Field(default_factory=list)
    affected_staff_ids: list[UUID] = Field(default_factory=list)
    criteria_triggered: list[int] = Field(default_factory=list)
    resolution_options: list[ResolutionOption] = Field(default_factory=list)


class SchedulingAlertResponse(BaseModel):
    """Response schema for a scheduling alert."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    alert_type: str
    severity: str
    title: str
    description: str
    affected_job_ids: list[UUID] | None = None
    affected_staff_ids: list[UUID] | None = None
    criteria_triggered: list[int] | None = None
    resolution_options: list[ResolutionOption]
    status: str
    schedule_date: date
    created_at: datetime


class ResolveAlertRequest(BaseModel):
    """Request to resolve an alert with a chosen action."""

    action: str
    parameters: dict[str, Any] | None = None


class DismissAlertRequest(BaseModel):
    """Request to dismiss a suggestion."""

    reason: str | None = None


# --- Change Requests ---


class ChangeRequestResponse(BaseModel):
    """Response schema for a change request."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    resource_id: UUID
    request_type: str
    details: dict[str, Any] | None = None
    affected_job_id: UUID | None = None
    recommended_action: str | None = None
    status: str
    created_at: datetime


class ApproveChangeRequest(BaseModel):
    """Request to approve a change request."""

    admin_notes: str | None = None


class DenyChangeRequest(BaseModel):
    """Request to deny a change request."""

    reason: str


# --- Pre-Job ---


class PreJobChecklist(BaseModel):
    """Pre-job requirements checklist for a resource."""

    job_type: str
    customer_name: str
    customer_address: str
    required_equipment: list[str]
    known_issues: list[str] = Field(default_factory=list)
    gate_code: str | None = None
    special_instructions: str | None = None
    estimated_duration: int  # minutes


class UpsellSuggestion(BaseModel):
    """Upsell opportunity based on customer equipment."""

    equipment_name: str
    age_years: float
    repair_count: int
    recommended_upgrade: str
    estimated_savings: Decimal


# --- Batch / Capacity / Utilization ---


class BatchScheduleRequest(BaseModel):
    """Request for batch schedule generation."""

    job_type: str
    customer_count: int
    weeks: int = 1
    zone_priority: list[str] | None = None


class BatchScheduleResponse(BaseModel):
    """Response from batch schedule generation."""

    total_jobs_scheduled: int
    weeks_covered: int
    schedule_by_week: dict[str, Any]
    unscheduled_count: int


class UtilizationReport(BaseModel):
    """Resource utilization report."""

    schedule_date: date
    resources: list[dict[str, Any]]
    average_utilization: float
    overbooked_count: int
    underutilized_count: int


class CapacityForecast(BaseModel):
    """Capacity forecast for upcoming weeks."""

    start_date: date
    end_date: date
    weeks: list[dict[str, Any]]
    recommendations: list[str]


# --- Configuration / Context ---


class SchedulingConfig(BaseModel):
    """Scheduling configuration with criteria weights and thresholds."""

    criteria: list[dict[str, Any]]
    thresholds: dict[str, Any] = Field(default_factory=dict)


class SchedulingContext(BaseModel):
    """Context for a scheduling operation."""

    schedule_date: date
    weather: dict[str, Any] | None = None
    traffic: dict[str, Any] | None = None
    backlog: dict[str, Any] | None = None
