"""
Scheduling alert model for AI-generated alerts and suggestions.

Stores alerts (critical conflicts) and suggestions (optimization
opportunities) generated by the AI scheduling engine's AlertEngine.

Validates: Requirements 11.1-11.5, 12.1-12.5, 19.1, 19.2
"""

from __future__ import annotations

from datetime import date, datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import Date, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from grins_platform.database import Base

if TYPE_CHECKING:
    from grins_platform.models.staff import Staff


class SchedulingAlert(Base):
    """AI-generated scheduling alert or suggestion.

    Alerts represent critical conflicts (red) requiring immediate
    attention. Suggestions represent optimization opportunities (green)
    that can be accepted or dismissed.

    Attributes:
        id: Unique identifier (UUID).
        alert_type: Type of alert (double_booking, skill_mismatch, etc.).
        severity: Alert severity (critical, suggestion).
        title: Display title.
        description: Detailed description.
        affected_job_ids: List of affected job UUIDs.
        affected_staff_ids: List of affected staff UUIDs.
        criteria_triggered: List of criterion numbers that triggered this.
        resolution_options: Available resolution actions with parameters.
        status: Current status (active, resolved, dismissed, expired).
        resolved_by: Admin who resolved the alert.
        resolved_action: Which resolution was chosen.
        resolved_at: When resolved.
        schedule_date: Which schedule date this alert pertains to.
        created_at: Record creation timestamp.
        updated_at: Last update timestamp.
    """

    __tablename__ = "scheduling_alerts"

    # Primary key
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # Classification
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Affected entities
    affected_job_ids: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
    )
    affected_staff_ids: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Criteria and resolution
    criteria_triggered: Mapped[list[int] | None] = mapped_column(
        JSONB,
        nullable=True,
    )
    resolution_options: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Status tracking
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="active",
    )
    resolved_by: Mapped[UUID | None] = mapped_column(
        ForeignKey("staff.id"),
        nullable=True,
    )
    resolved_action: Mapped[str | None] = mapped_column(String(50), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Schedule context
    schedule_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    resolver: Mapped[Staff | None] = relationship(
        "Staff",
        foreign_keys=[resolved_by],
    )

    def __repr__(self) -> str:
        """Return string representation."""
        return (
            f"<SchedulingAlert("
            f"id={self.id}, "
            f"alert_type='{self.alert_type}', "
            f"severity='{self.severity}', "
            f"status='{self.status}')>"
        )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "id": str(self.id),
            "alert_type": self.alert_type,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "affected_job_ids": self.affected_job_ids,
            "affected_staff_ids": self.affected_staff_ids,
            "criteria_triggered": self.criteria_triggered,
            "resolution_options": self.resolution_options,
            "status": self.status,
            "resolved_by": str(self.resolved_by) if self.resolved_by else None,
            "resolved_action": self.resolved_action,
            "resolved_at": (self.resolved_at.isoformat() if self.resolved_at else None),
            "schedule_date": (
                self.schedule_date.isoformat() if self.schedule_date else None
            ),
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
